NAME = proga

PATH_SRC = ./src/

HEADER = ./includes/

FLAG = -Wall -Wextra -Werror

OPTION = -c -I $(HEADER)

SRC = $(PATH_SRC)string.cpp $(PATH_SRC)strlen.cpp

OBJ = $(SRC.c=.o)

.c.o:
	g++ $(FLAG) $(OPTION) $< -o ${<:.c=.o}


$(NAME): ${OBJ}
	g++ -o proga ${OBJ}
		

all: $(NAME)

clean:
		rm -f $(OBJ) $(NAME)

fclean: clean
				
